name: Feature Request
description: Request a new feature
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature! Please check out the [open issues](https://github.com/avinash-vk/calcyourgpa/issues) to make sure that no one else has already opened an issue for the same feature.
  - type: textarea
    id: details
    attributes:
      label: What do you want to see?
      # description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you want to see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/avinash-vk/calcyourgpa/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
